/*
 * This source file was generated by the Gradle 'init' task
 */
package practica;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

      public     static int suma(int a, int b) {return a + b;}

        public static int resta(int a, int b) {return a - b;}
}
